//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by IPOP.rc
//
#define ID_CALIB_UPDATE                 3
#define IDC_CAL_UPDATE                  3
#define IDD_ABOUTBOX                    100
#define IDD_Disp_3D_View                101
#define IDD_DLG_CAMPARAMS               102
#define ID_SOWAS                        103
#define IDR_MAINFRAME                   128
#define IDR_IPOPTYPE                    129
#define IDB_BITMAP1                     131
#define IDD_DLG_POSE                    132
#define IDB_BITMAP2                     134
#define IDD_DLG_UNIVERSAL               137
#define IDD_DLG_IP_PARAMS               139
#define IDD_DLG_3D                      141
#define IDC_3D_PERSP_FRONT              1001
#define IDC_3D_PERSP_CAMERA             1002
#define IDC_3D_PERSP_LEFT               1003
#define IDC_3D_PERSP_RIGHT              1004
#define IDC_3D_PERSP_BACK               1005
#define IDC_Dlg_3D_StartView            1006
#define IDC_CAMPARAM_CAMMAT1            1007
#define IDC_CAMPARAM_CAMMAT2            1008
#define IDC_CAMPARAM_CAMMAT3            1009
#define IDC_CAMPARAM_CAMMAT4            1010
#define IDC_CAMPARAM_CAMMAT5            1011
#define IDC_CAMPARAM_CAMMAT6            1012
#define IDC_CAMPARAM_CAMMAT7            1013
#define IDC_CAMPARAM_CAMMAT8            1014
#define IDC_CAMPARAM_CAMMAT9            1015
#define IDC_CAMPARAM_DIST1              1016
#define IDC_CAMPARAM_DIST2              1017
#define IDC_CAMPARAM_DIST3              1018
#define IDC_CAMPARAM_DIST4              1019
#define IDC_CAMPARAM_PRINCX             1020
#define IDC_CAMPARAM_PRINCY             1021
#define IDC_BV_CAMPARAM_PIXNUMY         1022
#define IDC_BV_CAMPARAM_PIXNUMX         1023
#define IDC_BV_CAMPARAM_FOCLEN          1024
#define IDC_BV_CAMPARAM_PIXSIZEX        1025
#define IDC_BV_CAMPARAM_PIXSIZEY        1026
#define IDC_BV_CAMPARAM_CALCFOCLEN      1027
#define IDD_DLG_CHECKBOARD              1028
#define IDC_CAMCAL_ETALONX              1029
#define IDC_CAMCAL_ETALONY              1030
#define IDC_CAMCAL_ETALONWIDTH          1031
#define IDC_CAL_ROTX_NEG                1035
#define IDC_CAL_ROTX_POS                1036
#define IDC_CAL_NUMIT                   1038
#define IDC_CAL_ROTY_NEG                1039
#define IDC_CAL_ROTY_POS                1040
#define IDC_CAL_ROTZ_NEG                1041
#define IDC_CAL_ROTZ_POS                1042
#define IDC_CAL_TRANSZ_NEG              1043
#define IDC_CAL_TRANSZ_POS              1044
#define IDC_CAL_TRANSY_NEG              1045
#define IDC_CAL_TRANSY_POS              1046
#define IDC_CAL_TRANSX_NEG              1047
#define IDC_CAL_TRANSX_POS              1048
#define IDC_CAL_MACHINEREF_TRANSX_NEG   1049
#define IDC_CAL_CALMOD                  1050
#define IDC_CAL_MACHINEREF_TRANSX_POS   1050
#define IDC_CAL_MEASMOD                 1051
#define IDC_CAL_MACHINEREF_TRANSY_NEG   1051
#define IDC_CAL_MACHINEREFX             1052
#define IDC_CAL_MACHINEREFY             1053
#define IDC_CAL_MACHINEREFX2            1054
#define IDC_CAL_MACHINEREFROTZ          1054
#define IDC_CAL_MACHINEREFY2            1055
#define IDC_CAL_MACHINEREFROTX          1055
#define IDC_CAL_MACHINEREFX3            1056
#define IDC_CAL_WORKPIECE_TRANSX        1056
#define IDC_CAL_MACHINEREFY3            1057
#define IDC_CAL_WORKPIECE_ROTZ          1057
#define IDC_CAL_MACHINEREFX4            1058
#define IDC_CAL_WORKPIECE_TRANSY        1058
#define IDC_CAL_MACHINEREFY4            1059
#define IDC_CAL_MACHINEREF_TRANSY_POS   1059
#define IDC_3D_DRAW_PROJRAYS            1061
#define IDC_CAL_MACHINEREF_ROTZ_NEG     1061
#define IDC_3D_DRAW_CALPOINTS           1062
#define IDC_CAL_MACHINEREF_ROTZ_POS     1062
#define IDC_CAL_MACHINEREF_ROTX_NEG     1063
#define IDC_DLG_UNI_EDIT1               1063
#define IDC_CAL_WORKPIECE_TRANSX_NEG    1064
#define IDC_3D_DRAW_DISTANCES           1065
#define IDC_CAL_WORKPIECE_TRANSX_POS    1065
#define IDC_DLG_UNI_TEXT1               1065
#define IDC_CAL_MACHINEREF_ROTX_POS     1066
#define IDC_DLG_UNI_TEXT2               1066
#define IDC_IPPARAMS_BINTHRESH          1066
#define IDC_CAL_WORKPIECE_TRANSY_NEG    1067
#define IDC_DLG_UNI_EDIT2               1067
#define IDC_CAL_WORKPIECE_TRANSY_POS    1068
#define IDC_CAL_WORKPIECE_ROTZ_NEG      1070
#define IDC_CAL_WORKPIECE_ROTZ_POS      1071
#define IDC_IPPARAMS_HOUGHACCU180       1074
#define IDC_IPPARAMS_HOUGHACCU360       1075
#define IDC_IPPARAMS_HOUGHACCU540       1076
#define IDC_IPPARAMS_SHOWSTEPS          1077
#define IDC_IPPARAMS_HOUGHSENSIVITY     1078
#define IDC_CAL_SUMDISTANCES            1080
#define IDC_IPPARAMS_HOUGHSENSIVITY_POS 1081
#define IDC_IPPARAMS_HOUGHSENSIVITY_NEG 1082
#define IDC_AVTCAMERA1                  1082
#define IDC_IPPARAMS_BINTHRESH_POS      1083
#define IDC_DLG_POSE_SETASMACHREF       1083
#define IDC_IPPARAMS_BINTHRESH_NEG      1084
#define IDC_CAL_RotationX               1150
#define IDC_CAL_TranslationX            1204
#define IDC_CAL_TranslationY            1205
#define IDC_CAL_TranslationZ            1206
#define IDC_CAL_RotationY               1207
#define IDC_CAL_RotationZ               1208
#define IDC_IIPM_DLG_ROTART2            1273
#define ID_VIEW_CALIBRATE               32771
#define ID_VIEW_REGISTER                32772
#define ID_MFRM_OPENIMAGE               32773
#define ID_VIEW_FORWARD                 32774
#define ID_VIEW_BACK                    32775
#define ID_MFM_CAMPARAMS                32776
#define ID_MFM_LASTPIC                  32778
#define ID_MFM_CHESSBPARAMS             32779
#define ID_VIEW_CALIBRATE_INIT          32780
#define ID_VIEW_CALIBRATE_ONESTEP       32781
#define ID_MFM_POSEDLG                  32783
#define ID_MFRM_OPEN_CALIMAGE           32784
#define ID_MFRM_OPEN_REGIMAGE           32785
#define ID_REG_IP_BINARIZE              32786
#define ID_REG_IP_HOUGH                 32787
#define ID_REG_IP_EDGE                  32788
#define ID_REGISTRIEREN_VORVERARBEITUNG 32789
#define ID_IPPARAMS                     32790
#define ID_VIEW_MODER                   32793
#define ID_VIEW_MODEK                   32794
#define ID_VIDEO_START                  32795
#define ID_VIDEO_GRABFRAME              32796
#define ID_VIDEO_CHOOSESOURCE           32797
#define ID_PICVIEW_SAVEBMP              32799
#define ID_FILTERGRAPH_SOURCEDLG        32800
#define ID_VIDEO_INIT_DIRECTSHOW        32801
#define ID_VIDEO_DIRECTSHOW_CHOOSESOURCE 32802
#define ID_VIDEO_VFW_FORMATDLG          32803
#define ID_VIDEO_VFW_CHOOSEDISPLAY      32804
#define ID_VIDEO_PXC_INIT               32805
#define ID_VIDEO_PXC_GRAB               32806
#define ID_PXC_CAM1                     32807
#define ID_PXC_CAM2                     32808
#define ID_VIDEO_SNAPANDREG             32809
#define ID_REG_EROSION                  32811
#define ID_REG_FLOODFILL                32814

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        142
#define _APS_NEXT_COMMAND_VALUE         32815
#define _APS_NEXT_CONTROL_VALUE         1085
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
